#!/bin/bash
# Quick Start - Complete Deployment Guide
# This script shows all the commands needed to deploy

set -e

echo "╔════════════════════════════════════════════════════════╗"
echo "║   MS Tech Demo - Complete Deployment Guide             ║"
echo "║   Multi-Model AI Routing on Azure                      ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# ============================================================
echo "📝 STEP 1: Verify Your Setup"
echo "============================================================"
echo ""
echo "Subscription:"
az account show --query "name" -o tsv
echo ""
echo "Resource Group:"
az group show --name rg-ms-tech-demo1 --query "name" -o tsv
echo ""
echo "✅ Your setup is ready in westeurope region"
echo ""

# ============================================================
echo "📝 STEP 2: Create GitHub Repository"
echo "============================================================"
echo ""
echo "Go to: https://github.com/new"
echo "Fill in:"
echo "  Repository name: ms-tech-demo"
echo "  Description: Multi-model AI routing on Azure"
echo "  Visibility: Public (recommended for CI/CD)"
echo ""
echo "Then run:"
echo ""
echo "cd /Users/dilgamsharifov/Documents/ms-tech-demo1"
echo "git remote add origin https://github.com/YOUR_USERNAME/ms-tech-demo.git"
echo "git push -u origin main"
echo ""

# ============================================================
echo "📝 STEP 3: Add GitHub Secrets"
echo "============================================================"
echo ""
echo "Go to: GitHub Repo → Settings → Secrets and variables → Actions"
echo ""
echo "Add these secrets:"
echo ""
echo "1️⃣  VITE_API_URL"
echo "   https://mstech-demo-router-api.azurewebsites.net"
echo ""
echo "2️⃣  AzureAppService_PublishProfile_44751b3e1cc1412289a5ed70da06ca2f"
echo "   Run this command and copy the output:"
echo ""
echo "   az webapp deployment list-publishing-credentials \\"
echo "     --resource-group rg-ms-tech-demo1 \\"
echo "     --name mstech-demo-router-api \\"
echo "     --query publishingCredentials -o json"
echo ""
echo "3️⃣  AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_HILL_0DB554803"
echo "   First create the Static Web App (Step 4), then get token:"
echo ""
echo "   az staticwebapp secrets list \\"
echo "     --resource-group rg-ms-tech-demo1 \\"
echo "     --name mstech-demo-ui \\"
echo "     --query 'properties.apiToken' -o tsv"
echo ""

# ============================================================
echo "📝 STEP 4: Create Static Web App (Frontend)"
echo "============================================================"
echo ""
echo "Run this command:"
echo ""
echo "az staticwebapp create \\"
echo "  --name mstech-demo-ui \\"
echo "  --resource-group rg-ms-tech-demo1 \\"
echo "  --source https://github.com/YOUR_USERNAME/ms-tech-demo \\"
echo "  --location westeurope \\"
echo "  --branch main \\"
echo "  --app-location 'frontend/dist' \\"
echo "  --output-location ''"
echo ""
echo "Then get the API token and add it to GitHub Secrets (see Step 3.5)"
echo ""

# ============================================================
echo "📝 STEP 5: Deploy!"
echo "============================================================"
echo ""
echo "Make a change and push:"
echo ""
echo "cd /Users/dilgamsharifov/Documents/ms-tech-demo1"
echo "git add ."
echo "git commit -m 'First deployment'"
echo "git push origin main"
echo ""
echo "GitHub Actions will automatically deploy both:"
echo "  ✓ Backend to App Service"
echo "  ✓ Frontend to Static Web App"
echo ""

# ============================================================
echo "📝 STEP 6: Test Your Deployment"
echo "============================================================"
echo ""
echo "Test backend health:"
echo "curl https://mstech-demo-router-api.azurewebsites.net/health"
echo ""
echo "Test routing:"
echo "curl -X POST https://mstech-demo-router-api.azurewebsites.net/api/routePrompt \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"prompt\":\"Hello\",\"messages\":[]}'"
echo ""
echo "Visit frontend:"
echo "https://orange-hill-0db554803.7.azurestaticapps.net"
echo ""

# ============================================================
echo "🎉 Deployment Complete!"
echo "============================================================"
echo ""
echo "Your multi-model AI demo is now deployed on Azure!"
echo ""
echo "Architecture:"
echo "  React UI → Static Web App (westeurope)"
echo "      ↓"
echo "  FastAPI → App Service (westeurope)"
echo "      ↓"
echo "  Azure AI Foundry"
echo "      ├─ DeepSeek-V4-Flash (simple tasks)"
echo "      ├─ gpt-5.4-mini (routing/classifier)"
echo "      └─ gpt-5-pro-reasoning (complex tasks)"
echo ""
