# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'Build and deploy Python app to Azure Web App: mstech-demo-router-api'

on:
  push:
    branches:
    - main
    - feature/improve-model-routing
    - feature/reduce-router-latency
    - feature/voice-live
    - rag-feature
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: cd backend && python -m pip install -r requirements.txt

    - name: Package dependencies for App Service
      run: cd backend && python -m pip install -r requirements.txt --target .python_packages/lib/site-packages
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'mstech-demo-router-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_44751b3e1cc1412289a5ed70da06ca2f }}
        package: backend
